version: "3"
services:
  chat-app-frontend:
    build: ./frontend
    ports:
      - 3000:3000
  chat-app-backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - chat-app-db
  chat-app-db:
    image: mongo
    ports:
      - 27017:27017